name: pandaCD

on: [push]

jobs:
  echotest:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v1
      - name: dependencies install
        run: npm install
      - name: js
        run: node index.js
      - name: Run a one-line script
        run: echo Hello, world! world!!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
